name: wkramsey
favicon: null
layout_spectrum: 0.2689415253698826
typography_spectrum: 0.47445720597170293
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.8238528177607805
  lightness: 0.3897284818813205
  saturation: 0.6697321792598814
  rhythmicContrast: 0.9663730871398002
purpose: []
