name: wkramsey
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
opengraph: {}
color:
  saturation: 0.6697321792598814
  brandStrength: 0.7819549
  lightness: 0.3897284818813205
  brandColors:
    - '#131514'
    - '#FFFFFF'
    - '#B9CCD0'
    - '#727972'
    - '#333C39'
  rhythmicContrast: 0.9663730871398002
typography_spectrum: 0.736019
layout_spectrum: 0.4799499
analytics: {}
cta: {}
